### ISSUE TITLE
Scatter plot mouseover is not precise

### ISSUE THREAD

**Issue by AljoschaK** [dieterich-lab/medex#10]
Not sure if this is a bug coming from plotly directly - then it might be hard to fix, but if I mouseover a point in scatter plot, I see the numbers of a different point displayed: 

![image](https://user-images.githubusercontent.com/33421950/84123102-acf7cc00-aa39-11ea-903d-8eb947756006.png)

**Comment by Magdalena5** [comment]
It was a problem with Plotly JavaScript Graphing Library. I changed to Plotly Python Graphing Library. This solved the issue.
