### ISSUE TITLE
Histogram total number seems to be off

### ISSUE THREAD

**Issue by AljoschaK** [dieterich-lab/medex#11]
If I compare the histogram total number with the number I get from the tab "Simple statistics" for the same variable, There seems to be a difference...is there an explanation for this? Compare 6338 vs 6356?

![image](https://user-images.githubusercontent.com/33421950/84123284-ec261d00-aa39-11ea-867e-718c9a54ea7b.png)

**Comment by Magdalena5** [comment]
I solved the problem, here was problem in file that were missing some Cell_ID for condition.
