### ISSUE TITLE
Improve Coplot visualization

### ISSUE THREAD

**Issue by AljoschaK** [dieterich-lab/medex#6]
We currently have a representation that is similar to the R Coplot, but not quite nice. 
What we seek to represent is: We want to show different scatter plots of two continuous variables, and each scatter plot is again a combination of a categorical variable setting. Currently we have one scatter plot for each combination of categories. But we want something that is more appealing, more similar to the original R coplot, as described here: 
https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/coplot
http://www.unige.ch/ses/sococ/cl/r/scatcoplot.e.html

The result should look like: 
![image](https://user-images.githubusercontent.com/33421950/73191386-aff7bd00-4127-11ea-8994-08d69e108f44.png)

**Comment by Magdalena5** [comment]
I think that the coplots created in Medex have the same functionality, the difference is only in visualization. However, in Plotly, I didn't find the possibility of presenting the graphs in exactly the same way.
